### ISSUE TITLE
Add line height tests.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2-tests#245]
Add tests to support w3c/ttml2#1106.

**Comment by skynavga** [comment]
This test will be limited to verifying the semantic affect of adding `tts:fontSelectionStrategy` to  the list of style properties of _P_ for which _FF_ must match in order to be selected as _F0_ in step (4) of the algorithm defined for resolving the _used value_ of `normal` line height.

**Comment by nigelmegitt** [comment]
I understand the issue here. 

I don't like to introduce an additional dependency, and I'm concerned about the amount of work involved, but I think in principle it should be possible to test this if we allow ourselves to use the `#embedded-font` feature: we could arrange a test file that clearly produces a different line height when `tts:fontSelectionStrategy="character"` is used compared to `"auto"` in a similar way to the example given in the TTML2 section that defines [`tts:fontSelectionStrategy`](https://www.w3.org/TR/2020/CR-ttml2-20200128/#style-attribute-fontSelectionStrategy).

As I say, pragmatically, it may be too hard to write a test for this, but in that case one might reasonable ask why we thought it important to introduce `fontSelectionStrategy` at all.
